apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-monitor
spec:
  destination:
    name: ""
    namespace: ""
    server: "https://kubernetes.default.svc"
  source:
    path: config/monitoring/traefik
    repoURL: "https://github.com/sydrawat01/homelab.git"
    targetRevision: HEAD
  sources: []
  project: service-monitor
