apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime
spec:
  destination:
    name: ""
    namespace: "monitoring"
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://k3rnelpan1c-dev.github.io/uptime-kuma-helm/"
    targetRevision: 1.3.5
    chart: uptime-kuma
    helm:
      values: |
        serviceMonitor:
          enabled: true
        persistence:
          enabled: true
          storageClass: longhorn
        service:
          type: LoadBalancer
          loadBalancerIP: "10.0.0.210"
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 3310
          runAsGroup: 3310
          fsGroup: 3310
          fsGroupChangePolicy: "OnRootMismatch"
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
